- name: bug
  color: d73a4a
  description: 存在程序缺陷或错误
- name: enhancement
  color: a2eeef
  description: 新功能或改进建议
- name: question
  color: d876e3
  description: 一般性问题或咨询
- name: documentation
  color: 0075ca
  description: 文档相关问题
- name: duplicate
  color: cfd3d7
  description: 与现有 issue 重复
- name: invalid
  color: e4e669
  description: 无效 issue
- name: wontfix
  color: ffffff
  description: 不予解决
- name: in progress
  color: fbca04
  description: 正在处理中
- name: blocked
  color: 5319e7
  description: 受阻需要等待
- name: needs info
  color: 0e8a16
  description: 需要更多信息
- name: "priority: high"
  color: b60205
  description: 高优先级
- name: "priority: medium"
  color: fbca04
  description: 中等优先级
- name: "priority: low"
  color: 0052cc
  description: 低优先级
- name: command
  color: 1d76db
  description: 与指令相关的问题
- name: event
  color: 5319e7
  description: 与事件处理相关
- name: api
  color: 0e8a16
  description: 与 Discord API 相关
- name: config
  color: f9d0c4
  description: 配置相关
- name: localization
  color: 5319e7
  description: 本地化/多语言
- name: compatibility
  color: 0052cc
  description: 兼容性问题