name: CI Build

on: { push, pull_request, workflow_dispatch }

env:
  DOTNET_ROLL_FORWARD: "Major"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  PR_PROMPT: "::warning:: Build artifact will not be uploaded due to the workflow is triggered by pull request."

jobs:
  build:
    name: Build - ${{ matrix.os }} - ${{ matrix.dotnet-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet-version: [latest]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        env:
          IS_PR: ${{ !!github.head_ref }}
        run: |
          if ($env:IS_PR -eq "true") { echo $env:PR_PROMPT }
          $outputDir=$executioncontext.sessionstate.path.getunresolvedproviderpathfrompspath(".\publish\")
          dotnet publish -c Release --property:PublishDir=$outputDir --no-self-contained
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !github.head_ref }}
        with:
          name: RitsukageBotForDiscord - ${{ matrix.os }} - ${{ matrix.dotnet-version }}
          path: publish/